/* Selecciono la base de datos donde quiero insertar los datos */
USE pandora_tenis;

/*Categorias: RAQUETA - ROPA - ACCESORIOS (seria cualquier cosa menos el resto de categorias)*/
/* Insertar productos */
INSERT INTO products (category, name, price, discount, cover, description) VALUES
('RAQUETA','Wilson Blade 98 v9', 279999.00, 0, '/app/assets/imgs/products/wilson-blade-98-v9.png', 'Raqueta de tenis Wilson con gran control y precisión.'),
('RAQUETA','Wilson Pro Staff X v14', 299999.00, 0, '/app/assets/imgs/products/wilson-pro-staff-x-v14.png', 'Raqueta Wilson Pro Staff con diseño clásico y potencia moderna.'),
('RAQUETA','Babolat Pure Drive 2024', 285000.00, 0, '/app/assets/imgs/products/babolat-pure-drive-2024.png', 'Raqueta Babolat Pure Drive con excelente equilibrio potencia-control.'),
('RAQUETA','Babolat Aero 98 Rafa Origin', 325000.00, 0, '/app/assets/imgs/products/babolat-aero-98-rafa-origin.png', 'Raqueta de tenis Babolat edición Rafa Nadal.'),
('RAQUETA','Head Speed MP 2024', 310000.00, 0, '/app/assets/imgs/products/head-speed-mp-2024.png', 'Raqueta Head Speed MP ideal para jugadores agresivos.'),
('RAQUETA','Head Radical Pro', 295000.00, 0, '/app/assets/imgs/products/head-radical-pro.png', 'Raqueta Head Radical Pro para control y versatilidad.'),
('RAQUETA','Yonex Ezone 100', 278000.00, 0, '/app/assets/imgs/products/yonex-ezone-100.png', 'Raqueta Yonex Ezone 100 con excelente potencia y confort.'),
('RAQUETA','Yonex VCore 98', 289000.00, 0, '/app/assets/imgs/products/yonex-vcore-98.png', 'Raqueta Yonex VCore para jugadores avanzados.'),
('RAQUETA','Wilson Clash 100 v2', 269000.00, 0, '/app/assets/imgs/products/wilson-clash-100-v2.png', 'Raqueta Wilson Clash con gran flexibilidad y confort.'),
('RAQUETA','Dunlop FX 500 LS', 255000.00, 0, '/app/assets/imgs/products/dunlop-fx-500-ls.png', 'Raqueta Dunlop ligera para jugadores intermedios.'),
('RAQUETA','Wilson Bela Elite V2', 310000.00, 0, '/app/assets/imgs/products/wilson-bela-elite-v2.png', 'Pala de pádel Wilson Bela Elite con núcleo de carbono.'),
('RAQUETA','Wilson Ultra Pro V2', 298000.00, 0, '/app/assets/imgs/products/wilson-ultra-pro-v2.png', 'Pala de pádel Wilson Ultra Pro de gran potencia.'),
('RAQUETA','Head Extreme Pro 2024', 279000.00, 0, '/app/assets/imgs/products/head-extreme-pro-2024.png', 'Pala de pádel Head Extreme Pro para jugadores ofensivos.'),
('RAQUETA','Head Delta Motion 2024', 255000.00, 0, '/app/assets/imgs/products/head-delta-motion-2024.png', 'Pala Head Delta Motion con amplio punto dulce.'),
('RAQUETA','Babolat Technical Viper', 295000.00, 0, '/app/assets/imgs/products/babolat-technical-viper.png', 'Pala Babolat Technical Viper para potencia extrema.'),
('RAQUETA','Babolat Air Viper', 285000.00, 0, '/app/assets/imgs/products/babolat-air-viper.png', 'Pala ligera Babolat Air Viper con control y maniobrabilidad.'),
('ROPA','Nox AT10 Luxury Genius 18K', 275000.00, 0, '/app/assets/imgs/products/nox-at10-luxury-genius-18k.png', 'Pala Nox AT10 Luxury con superficie de carbono 18K.'),
('ROPA','Nox ML10 Pro Cup', 249000.00, 0, '/app/assets/imgs/products/nox-ml10-pro-cup.png', 'Clásica pala Nox ML10 con gran control.'),
('ROPA','Bullpadel Vertex 04', 299000.00, 0, '/app/assets/imgs/products/bullpadel-vertex-04.png', 'Pala Bullpadel Vertex 04 para juego de ataque.'),
('ROPA','Bullpadel Hack 03 2024', 315000.00, 0, '/app/assets/imgs/products/bullpadel-hack-03-2024.png', 'Pala Bullpadel Hack 03 usada por Paquito Navarro.'),
('ACCESORIO','Adidas Metalbone 3.3', 305000.00, 0, '/app/assets/imgs/products/adidas-metalbone-3.3.png', 'Pala Adidas Metalbone con sistema de pesos regulables.'),
('ACCESORIO','Adidas Adipower Ctrl 3.3', 295000.00, 0, '/app/assets/imgs/products/adidas-adipower-ctrl-3.3.png', 'Pala Adidas Adipower Control 3.3 para precisión.'),
('ACCESORIO','Siux Electra ST2', 278000.00, 0, '/app/assets/imgs/products/siux-electra-st2.png', 'Pala Siux Electra con carbono 12K y tacto firme.'),
('ACCESORIO','Siux Diablo Revolution', 289000.00, 0, '/app/assets/imgs/products/siux-diablo-revolution.png', 'Pala Siux Diablo Revolution con balance medio.'),
('ACCESORIO','StarVie Metheora Dual', 272000.00, 0, '/app/assets/imgs/products/starvie-metheora-dual.png', 'Pala StarVie Metheora con doble densidad para control.'),
('ACCESORIO','StarVie Raptor Evolution', 268000.00, 0, '/app/assets/imgs/products/starvie-raptor-evolution.png', 'Pala StarVie Raptor con gran salida de bola.'),
('ACCESORIO','Wilson Kaos Swift 2.0', 145000.00, 0, '/app/assets/imgs/products/wilson-kaos-swift-2.0.png', 'Zapatillas Wilson Kaos Swift para velocidad y agarre.'),
('ACCESORIO','Adidas Barricade 2024', 155000.00, 0, '/app/assets/imgs/products/adidas-barricade-2024.png', 'Zapatillas adidas Barricade para máxima estabilidad.'),
('ACCESORIO','Babolat Jet Mach 3', 148000.00, 0, '/app/assets/imgs/products/babolat-jet-mach-3.png', 'Zapatillas Babolat Jet Mach 3 ultraligeras.'),
('ACCESORIO','Head Revolt Pro 4.5', 142000.00, 0, '/app/assets/imgs/products/head-revolt-pro-4.5.png', 'Zapatillas Head Revolt Pro 4.5 para máxima tracción.'),
('ACCESORIO','Head Sprint Pro 3.5', 139000.00, 0, '/app/assets/imgs/products/head-sprint-pro-3.5.png', 'Zapatillas Head Sprint Pro 3.5 ligeras y estables.'),
('ACCESORIO','Yonex Power Cushion Eclipsion 5', 158000.00, 0, '/app/assets/imgs/products/yonex-power-cushion-eclipsion-5.png', 'Zapatillas Yonex Eclipsion 5 con amortiguación superior.'),
('ACCESORIO','Asics Gel Resolution 9', 160000.00, 0, '/app/assets/imgs/products/asics-gel-resolution-9.png', 'Zapatillas Asics Gel Resolution 9 con soporte premium.'),
('ACCESORIO','Asics Court FF 3 Novak', 175000.00, 0, '/app/assets/imgs/products/asics-court-ff-3-novak.png', 'Zapatillas Asics Court FF 3 Novak Djokovic edition.'),
('ACCESORIO','Lacoste AG-LT23 Ultra', 180000.00, 0, '/app/assets/imgs/products/lacoste-ag-lt23-ultra.png', 'Zapatillas Lacoste AG-LT23 con amortiguación avanzada.'),
('ACCESORIO','Wilson Rush Pro 4.0', 152000.00, 0, '/app/assets/imgs/products/wilson-rush-pro-4.0.png', 'Zapatillas Wilson Rush Pro 4.0 con máxima tracción.'),
('ACCESORIO','Adidas Ubersonic 5', 149000.00, 0, '/app/assets/imgs/products/adidas-ubersonic-5.png', 'Zapatillas adidas Ubersonic 5 para velocidad.'),
('ACCESORIO','Babolat SFX 3', 132000.00, 0, '/app/assets/imgs/products/babolat-sfx-3.png', 'Zapatillas Babolat SFX 3 cómodas para todo tipo de pistas.'),
('ACCESORIO','Joma Slam Pro Men', 118000.00, 0, '/app/assets/imgs/products/joma-slam-pro-men.png', 'Zapatillas Joma Slam Pro para padel.'),
('ACCESORIO','Bullpadel Flow Hybrid Fly', 127000.00, 0, '/app/assets/imgs/products/bullpadel-flow-hybrid-fly.png', 'Zapatillas Bullpadel Flow Hybrid Fly mujer.'),
('ACCESORIO','Wilson Bela Tour White', 310999.00, 0, '/app/assets/imgs/products/wilson-bela-tour-white.png', 'Zapatillas Wilson Bela Tour blancas para padel.'),
('ACCESORIO','Wilson Kaos Mirage 2024', 136000.00, 0, '/app/assets/imgs/products/wilson-kaos-mirage-2024.png', 'Zapatillas Wilson Kaos Mirage edición 2024.'),
('ACCESORIO','Head Motion Pro Padel', 148500.00, 0, '/app/assets/imgs/products/head-motion-pro-padel.png', 'Zapatillas Head Motion Pro diseñadas para padel.'),
('ACCESORIO','Adidas CourtJam Control 3', 129000.00, 0, '/app/assets/imgs/products/adidas-courtjam-control-3.png', 'Zapatillas adidas CourtJam Control 3 para control y confort.'),
('ACCESORIO','Nox AT10 Pro Padel Shoes', 146700.00, 0, '/app/assets/imgs/products/nox-at10-pro-padel-shoes.png', 'Zapatillas Nox AT10 Pro con gran estabilidad lateral.'),
('ACCESORIO','Babolat Play Crew T-Shirt', 42000.00, 10, '/app/assets/imgs/products/babolat-play-crew-t-shirt.png', 'Remera técnica Babolat Play Crew para entrenamiento.'),
('ACCESORIO','Wilson Team Polo', 48000.00, 0, '/app/assets/imgs/products/wilson-team-polo.png', 'Polo Wilson Team ligero y transpirable.'),
('ACCESORIO','Adidas Club 3-Stripes Tee', 45000.00, 5, '/app/assets/imgs/products/adidas-club-3-stripes-tee.png', 'Remera adidas Club con diseño clásico.'),
('ACCESORIO','Head Performance Shorts', 52000.00, 0, '/app/assets/imgs/products/head-performance-shorts.png', 'Short Head Performance de secado rápido.'),
('ACCESORIO','Babolat Play Skirt Women', 57000.00, 0, '/app/assets/imgs/products/babolat-play-skirt-women.png', 'Pollera deportiva Babolat Play para mujer.'),
('ACCESORIO','Wilson Team Skirt', 55000.00, 0, '/app/assets/imgs/products/wilson-team-skirt.png', 'Pollera Wilson Team ligera y elástica.'),
('ROPA','Adidas Club Shorts', 49000.00, 0, '/app/assets/imgs/products/adidas-club-shorts.png', 'Shorts adidas Club con ajuste cómodo.'),
('ROPA','Head Club Jacket', 78000.00, 0, '/app/assets/imgs/products/head-club-jacket.png', 'Campera Head Club ideal para entrenamiento.'),
('ACCESORIO','Babolat Exercise Hoodie', 85000.00, 10, '/app/assets/imgs/products/babolat-exercise-hoodie.png', 'Buzo Babolat Exercise con capucha y bolsillo canguro.'),
('ACCESORIO','Wilson Team 12 Pack Bag', 195000.00, 0, '/app/assets/imgs/products/wilson-team-12-pack-bag.png', 'Bolso Wilson para 12 raquetas con compartimentos térmicos.'),
('ACCESORIO','Babolat RH12 Pure Aero Rafa', 210000.00, 0, '/app/assets/imgs/products/babolat-rh12-pure-aero-rafa.png', 'Bolso Babolat Pure Aero edición Rafa Nadal.'),
('ACCESORIO','Head Tour Team Monstercombi', 188000.00, 0, '/app/assets/imgs/products/head-tour-team-monstercombi.png', 'Bolso Head Tour Team grande para competición.'),
('ACCESORIO','Yonex Pro 9 Racket Bag', 170000.00, 0, '/app/assets/imgs/products/yonex-pro-9-racket-bag.png', 'Bolso Yonex Pro para 9 raquetas y accesorios.'),
('ACCESORIO','Adidas Multigame Padel Bag', 160000.00, 0, '/app/assets/imgs/products/adidas-multigame-padel-bag.png', 'Bolso adidas Multigame para palas de padel.'),
('ACCESORIO','Bullpadel Vertex Padel Bag', 174000.00, 0, '/app/assets/imgs/products/bullpadel-vertex-padel-bag.png', 'Paletero Bullpadel Vertex con compartimentos térmicos.'),
('ACCESORIO','Head Sprint Pro 3.5', 139000.00, 0, '/app/assets/imgs/products/head-sprint-pro-3.5.png', 'Zapatillas Head Sprint Pro 3.5 ligeras y estables.'),
('ACCESORIO','Yonex Power Cushion Eclipsion 5', 158000.00, 0, '/app/assets/imgs/products/yonex-power-cushion-eclipsion-5.png', 'Zapatillas Yonex Eclipsion 5 con amortiguación superior.'),
('ACCESORIO','Asics Gel Resolution 9', 160000.00, 0, '/app/assets/imgs/products/asics-gel-resolution-9.png', 'Zapatillas Asics Gel Resolution 9 con soporte premium.'),
('ACCESORIO','Asics Court FF 3 Novak', 175000.00, 0, '/app/assets/imgs/products/asics-court-ff-3-novak.png', 'Zapatillas Asics Court FF 3 Novak Djokovic edition.'),
('ACCESORIO','Lacoste AG-LT23 Ultra', 180000.00, 0, '/app/assets/imgs/products/lacoste-ag-lt23-ultra.png', 'Zapatillas Lacoste AG-LT23 con amortiguación avanzada.'),
('ACCESORIO','Wilson Rush Pro 4.0', 152000.00, 0, '/app/assets/imgs/products/wilson-rush-pro-4.0.png', 'Zapatillas Wilson Rush Pro 4.0 con máxima tracción.'),
('ACCESORIO','Adidas Ubersonic 5', 149000.00, 0, '/app/assets/imgs/products/adidas-ubersonic-5.png', 'Zapatillas adidas Ubersonic 5 para velocidad.'),
('ACCESORIO','Babolat SFX 3', 132000.00, 0, '/app/assets/imgs/products/babolat-sfx-3.png', 'Zapatillas Babolat SFX 3 cómodas para todo tipo de pistas.'),
('ACCESORIO','Joma Slam Pro Men', 118000.00, 0, '/app/assets/imgs/products/joma-slam-pro-men.png', 'Zapatillas Joma Slam Pro para padel.'),
('ACCESORIO','Bullpadel Flow Hybrid Fly', 127000.00, 0, '/app/assets/imgs/products/bullpadel-flow-hybrid-fly.png', 'Zapatillas Bullpadel Flow Hybrid Fly mujer.'),
('ACCESORIO','Wilson Bela Tour White', 310999.00, 0, '/app/assets/imgs/products/wilson-bela-tour-white.png', 'Zapatillas Wilson Bela Tour blancas para padel.'),
('ACCESORIO','Wilson Kaos Mirage 2024', 136000.00, 0, '/app/assets/imgs/products/wilson-kaos-mirage-2024.png', 'Zapatillas Wilson Kaos Mirage edición 2024.'),
('ACCESORIO','Head Motion Pro Padel', 148500.00, 0, '/app/assets/imgs/products/head-motion-pro-padel.png', 'Zapatillas Head Motion Pro diseñadas para padel.'),
('ACCESORIO','Adidas CourtJam Control 3', 129000.00, 0, '/app/assets/imgs/products/adidas-courtjam-control-3.png', 'Zapatillas adidas CourtJam Control 3 para control y confort.'),
('ACCESORIO','Nox AT10 Pro Padel Shoes', 146700.00, 0, '/app/assets/imgs/products/nox-at10-pro-padel-shoes.png', 'Zapatillas Nox AT10 Pro con gran estabilidad lateral.'),
('ACCESORIO','Babolat Play Crew T-Shirt', 42000.00, 10, '/app/assets/imgs/products/babolat-play-crew-t-shirt.png', 'Remera técnica Babolat Play Crew para entrenamiento.'),
('ACCESORIO','Wilson Team Polo', 48000.00, 0, '/app/assets/imgs/products/wilson-team-polo.png', 'Polo Wilson Team ligero y transpirable.'),
('ACCESORIO','Adidas Club 3-Stripes Tee', 45000.00, 5, '/app/assets/imgs/products/adidas-club-3-stripes-tee.png', 'Remera adidas Club con diseño clásico.'),
('ACCESORIO','Head Performance Shorts', 52000.00, 0, '/app/assets/imgs/products/head-performance-shorts.png', 'Short Head Performance de secado rápido.'),
('ACCESORIO','Babolat Play Skirt Women', 57000.00, 0, '/app/assets/imgs/products/babolat-play-skirt-women.png', 'Pollera deportiva Babolat Play para mujer.'),
('ACCESORIO','Wilson Team Skirt', 55000.00, 0, '/app/assets/imgs/products/wilson-team-skirt.png', 'Pollera Wilson Team ligera y elástica.'),
('ACCESORIO','Adidas Club Shorts', 49000.00, 0, '/app/assets/imgs/products/adidas-club-shorts.png', 'Shorts adidas Club con ajuste cómodo.'),
('ACCESORIO','Head Club Jacket', 78000.00, 0, '/app/assets/imgs/products/head-club-jacket.png', 'Campera Head Club ideal para entrenamiento.'),
('ACCESORIO','Babolat Exercise Hoodie', 85000.00, 10, '/app/assets/imgs/products/babolat-exercise-hoodie.png', 'Buzo Babolat Exercise con capucha y bolsillo canguro.'),
('ACCESORIO','Wilson Team 12 Pack Bag', 195000.00, 0, '/app/assets/imgs/products/wilson-team-12-pack-bag.png', 'Bolso Wilson para 12 raquetas con compartimentos térmicos.'),
('ACCESORIO','Babolat RH12 Pure Aero Rafa', 210000.00, 0, '/app/assets/imgs/products/babolat-rh12-pure-aero-rafa.png', 'Bolso Babolat Pure Aero edición Rafa Nadal.'),
('ACCESORIO','Head Tour Team Monstercombi', 188000.00, 0, '/app/assets/imgs/products/head-tour-team-monstercombi.png', 'Bolso Head Tour Team grande para competición.'),
('ACCESORIO','Yonex Pro 9 Racket Bag', 170000.00, 0, '/app/assets/imgs/products/yonex-pro-9-racket-bag.png', 'Bolso Yonex Pro para 9 raquetas y accesorios.'),
('ACCESORIO','Adidas Multigame Padel Bag', 160000.00, 0, '/app/assets/imgs/products/adidas-multigame-padel-bag.png', 'Bolso adidas Multigame para palas de padel.'),
('ACCESORIO','Bullpadel Vertex Padel Bag', 174000.00, 0, '/app/assets/imgs/products/bullpadel-vertex-padel-bag.png', 'Paletero Bullpadel Vertex con compartimentos térmicos.'),
('ACCESORIO','Wilson Blade Super Tour 15 Pack', 225000.00, 0, '/app/assets/imgs/products/wilson-blade-super-tour-15-pack.png', 'Bolso Wilson Blade Super Tour para 15 raquetas.'),
('ACCESORIO','Babolat Pure Aero Rafa Backpack', 115000.00, 0, '/app/assets/imgs/products/babolat-pure-aero-rafa-backpack.png', 'Mochila Babolat Pure Aero Rafa Nadal edition.'),
('ACCESORIO','Head Djokovic 12R Monstercombi', 232000.00, 0, '/app/assets/imgs/products/head-djokovic-12r-monstercombi.png', 'Bolso Head Djokovic 12R con compartimento térmico.'),
('ACCESORIO','Yonex Team Backpack 2024', 99000.00, 0, '/app/assets/imgs/products/yonex-team-backpack-2024.png', 'Mochila Yonex Team con compartimiento para laptop.'),
('ACCESORIO','Adidas Adipower CTRL Team', 265000.00, 0, '/app/assets/imgs/products/adidas-adipower-ctrl-team.png', 'Pala Adidas Adipower CTRL Team de control y precisión.'),
('ACCESORIO','Bullpadel Ionic Power 2024', 275000.00, 0, '/app/assets/imgs/products/bullpadel-ionic-power-2024.png', 'Pala Bullpadel Ionic Power para pegadores.'),
('ACCESORIO','Siux Fenix IV Pro', 289000.00, 0, '/app/assets/imgs/products/siux-fenix-iv-pro.png', 'Pala Siux Fenix IV Pro con gran equilibrio y control.'),
('ACCESORIO','StarVie Triton Pro', 280000.00, 0, '/app/assets/imgs/products/starvie-triton-pro.png', 'Pala StarVie Triton Pro para potencia máxima.'),
('ACCESORIO','Nox ML10 Luxury Bahia', 272000.00, 0, '/app/assets/imgs/products/nox-ml10-luxury-bahia.png', 'Pala Nox ML10 Bahia con tacto medio y control.'),
('ACCESORIO','Wilson Ultra Elite V2', 259000.00, 0, '/app/assets/imgs/products/wilson-ultra-elite-v2.png', 'Pala Wilson Ultra Elite ideal para jugadores avanzados.'),
('ACCESORIO','Adidas Avacourt Women', 152000.00, 0, '/app/assets/imgs/products/adidas-avacourt-women.png', 'Zapatillas adidas Avacourt diseñadas para mujeres.'),
('ACCESORIO','Babolat Propulse Fury 3', 149000.00, 0, '/app/assets/imgs/products/babolat-propulse-fury-3.png', 'Zapatillas Babolat Propulse Fury 3 con amortiguación renovada.'),
('ACCESORIO','Head Sprint Team 3.5', 132000.00, 0, '/app/assets/imgs/products/head-sprint-team-3.5.png', 'Zapatillas Head Sprint Team ligeras y cómodas.'),
('ACCESORIO','Wilson Rush Pro Ace', 138000.00, 0, '/app/assets/imgs/products/wilson-rush-pro-ace.png', 'Zapatillas Wilson Rush Pro Ace para todo tipo de pista.'),
('ACCESORIO','Yonex Sonicage 3', 141000.00, 0, '/app/assets/imgs/products/yonex-sonicare-3.png', 'Zapatillas Yonex Sonicage 3 ligeras y resistentes.'),
('ACCESORIO','Lacoste AG-LT21 Ultra', 172000.00, 0, '/app/assets/imgs/products/lacoste-ag-lt21-ultra.png', 'Zapatillas Lacoste AG-LT21 con suela Michelin.'),
('ACCESORIO','Joma Slam WPT 2024', 120000.00, 0, '/app/assets/imgs/products/joma-slam-wpt-2024.png', 'Zapatillas Joma Slam edición World Padel Tour.'),
('ACCESORIO','Nox AT Pro Shoes Women', 145000.00, 0, '/app/assets/imgs/products/nox-at-pro-shoes-women.png', 'Zapatillas Nox AT Pro para jugadoras exigentes.'),
('ACCESORIO','Bullpadel Vertex Hybrid Fly 2024', 153000.00, 0, '/app/assets/imgs/products/bullpadel-vertex-hybrid-fly-2024.png', 'Zapatillas Bullpadel Vertex Hybrid Fly con suela clay.'),
('ACCESORIO','Adidas Defiant Speed', 140000.00, 0, '/app/assets/imgs/products/adidas-defiant-speed.png', 'Zapatillas adidas Defiant Speed ligeras y reactivas.'),
('ACCESORIO','Wilson Pro Staff 97 v14', 295000.00, 0, '/app/assets/imgs/products/wilson-pro-staff-97-v14.png', 'Raqueta Wilson Pro Staff 97 con marco de grafito.'),
('ACCESORIO','Head Prestige MP 2024', 305000.00, 0, '/app/assets/imgs/products/head-prestige-mp-2024.png', 'Raqueta Head Prestige MP para control absoluto.'),
('ACCESORIO','Babolat Pure Strike 16x19', 282000.00, 0, '/app/assets/imgs/products/babolat-pure-strike-16x19.png', 'Raqueta Babolat Pure Strike con respuesta firme.'),
('ACCESORIO','Yonex Percept 100D', 289000.00, 0, '/app/assets/imgs/products/yonex-percept-100d.png', 'Raqueta Yonex Percept 100D con control y precisión.'),
('ACCESORIO','Wilson Shift 99 V1', 275000.00, 0, '/app/assets/imgs/products/wilson-shift-99-v1.png', 'Raqueta Wilson Shift 99 con flexibilidad dinámica.'),
('ACCESORIO','Head Boom Pro 2024', 280000.00, 0, '/app/assets/imgs/products/head-boom-pro-2024.png', 'Raqueta Head Boom Pro con excelente potencia y confort.'),
('ACCESORIO','Babolat Pure Aero Team', 277000.00, 0, '/app/assets/imgs/products/babolat-pure-aero-team.png', 'Raqueta Babolat Pure Aero Team ligera y maniobrable.'),
('ACCESORIO','Adidas Metalbone HRD+ 3.3', 312000.00, 0, '/app/assets/imgs/products/adidas-metalbone-hrd-3.3.png', 'Pala adidas Metalbone HRD+ 3.3 de alta rigidez.'),
('ACCESORIO','Siux Pegasus Graphene 2K', 293000.00, 0, '/app/assets/imgs/products/siux-pegasus-graphene-2k.png', 'Pala Siux Pegasus Graphene 2K con potencia controlada.'),
('ACCESORIO','StarVie Aquila Space Pro', 270000.00, 0, '/app/assets/imgs/products/starvie-aquila-space-pro.png', 'Pala StarVie Aquila Space Pro versátil y equilibrada.');
